services:
  - type: web
    name: notes-app-backend
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        scope: secret
      - key: UPSTASH_REDIS_REST_URL
        scope: secret
      - key: UPSTASH_REDIS_REST_TOKEN
        scope: secret
      - key: FRONTEND_URL
        value: https://notes-taking-app-1-sk6o.onrender.com
        # Update this with your actual Render frontend URL after deployment
